name: build-html

on:
  push:
    branches:
      master

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          token: ${{secrets.PAT}}
      - name: Create build directory
        run: mkdir build
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          cache: 'pip'
      - name: Install markmap
        run: npm install -g markmap-cli
      - name: Run generator.py
        run: python generator.py
      - name: Checkout and push to html branch
        run: |
          git config user.email "<>"
          git config user.name "github-actions[bot]"
          git fetch origin
          git checkout html
          mv build/*.html .
          git commit -m "chore: :bento: update"
          git push
