name: build-html

on:
  push:
    branches:
      master

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          token: ${{secrets.PAT}}
      - name: Create build directory
        run: mkdir build
      - name: Install pandoc
        run: sudo apt-get install -y pandoc
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install markmap
        run: npm install -g markmap-cli
      - name: Run generator.py
        run: python generator.py
      - name: Specify git user config
        run: |
          git config user.email "<>"
          git config user.name "github-actions[bot]"
      - name: Checkout to html branch
        run: |
          git fetch origin
          git checkout html
      - name: Update files
        run: mv build/*.html .
      - name: Make commit to html branch
        run: |
          git add -A
          git commit -m "chore: :bento: update" || true
          git push
